export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'

export const RETRO_LIST_REQUEST = 'RETRO_LIST_REQUEST'
export const RETRO_LIST_SUCCESS = 'RETRO_LIST_SUCCESS'
export const RETRO_LIST_FAIL = 'RETRO_LIST_FAIL'

export const COMPUTER_LAPTOP_LIST_REQUEST = 'COMPUTER_LAPTOP_LIST_REQUEST'
export const COMPUTER_LAPTOP_LIST_SUCCESS = 'COMPUTER_LAPTOP_LIST_SUCCESS'
export const COMPUTER_LAPTOP_LIST_FAIL = 'COMPUTER_LAPTOP_LIST_FAIL'

export const SMARTPHONE_LIST_REQUEST = 'SMARTPHONE_LIST_REQUEST'
export const SMARTPHONE_LIST_SUCCESS = 'SMARTPHONE_LIST_SUCCESS'
export const SMARTPHONE_LIST_FAIL = 'SMARTPHONE_LIST_FAIL'

export const VR_LIST_REQUEST = 'VR_LIST_REQUEST'
export const VR_LIST_SUCCESS = 'VR_LIST_SUCCESS'
export const VR_LIST_FAIL = 'VR_LIST_FAIL'

export const ALL_PRODUCTS_REQUEST = 'ALL_PRODUCTS_REQUEST'
export const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS'
export const ALL_PRODUCTS_FAIL = 'ALL_PRODUCTS_FAIL'

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST'
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL'

